export const images = {
  skillLogos: {
    afterEffects: "/assets/skill_logos/after_effects.png",
    arduino: "/assets/skill_logos/arduino.png",
    django: "/assets/skill_logos/django.png",
    express: "/assets/skill_logos/express.png",
    firebase: "/assets/skill_logos/firebase.png",
    illustrator: "/assets/skill_logos/illustrator.png",
    javascript: "/assets/skill_logos/javascript.png",
    kicad: "/assets/skill_logos/kicad.png",
    mongodb: "/assets/skill_logos/mongodb.png",
    nextjs: "/assets/skill_logos/nextjs.png",
    node: "/assets/skill_logos/node.png",
    photoshop: "/assets/skill_logos/photoshop.png",
    premierePro: "/assets/skill_logos/premiere_pro.png",
    python: "/assets/skill_logos/python.png",
    raspberryPi: "/assets/skill_logos/raspberry_pi.png",
    socketio: "/assets/skill_logos/socketio.png",
    solidworks: "/assets/skill_logos/solidworks.png",
    sqlite: "/assets/skill_logos/sqlite.png",
    styledComponents: "/assets/skill_logos/styled_components.png",
    tailwind: "/assets/skill_logos/tailwindcss.png",
    react: "/assets/skill_logos/react.png",
    redux: "/assets/skill_logos/redux.png",
    supabase: "/assets/skill_logos/supabase.png",
    typescript: "/assets/skill_logos/typescript.png",
    chakraUI: "/assets/skill_logos/chakra-ui.png",
    sql: "/assets/skill_logos/sql.webp",
    canvas: "/assets/skill_logos/canvas.svg",
  },
  icons: {
    github: "/assets/icons/github.svg",
    linkedin: "/assets/icons/linkedin.svg",
    instagram: "/assets/icons/instagram.svg",
  },
};
